version: '3.7'

services:
    node:
        image: klasterio/node:1.0.28
        environment:
          - KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
          - PORT=3000
          - REDIS_HOST=redis
          - REDIS_PORT=6379
        ports:
          - "3000:3000"
        links:
          - redis
          - anvil
        volumes:
          - ./logs:/logs
          - ./keystore:/usr/src/app/keystore
          - ./chains:/usr/src/app/chains
    anvil:
        image: ghcr.io/foundry-rs/foundry:latest
        ports: ["8545:8545"]
        entrypoint:
          ["anvil", "--host", "0.0.0.0", "--block-time", "0.1", "--silent"]
    redis:
        image: redis:alpine
        restart: always
        command: redis-server --dir /data --save 60 1 --appendonly yes --loglevel warning
        volumes:
          - ./redis-data:/data
volumes:
    keystore:
    chains:
    redis-data:
    logs:
